### ISSUE TITLE
[Enhancement] BM25 ranking

### ISSUE THREAD

**Issue by aley1** [koculu/ZoneTree.FullTextSearch#11]
Hi,

Are you planning to add any document ranking such as BM25 to the search engine?

That would be a very useful feature to have,

**Comment by koculu** [comment]
Hi @aley1,

BM25 ranking is planned, but it's not a priority at the moment. In the meantime, you can calculate BM25 externally using the HashedSearchEngine.

Thanks for the suggestion!
